version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: abcd123
      MYSQL_DATABASE: lms 

    ports:
      - "3306:3306"  
    volumes:
      - my-db:/var/lib/mysql
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10

  web:
    build: .
    command: ['/bin/bash', '-c', 'python3 manage.py migrate && python manage.py runserver 0.0.0.0:8000']
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_NAME=lms
      - DATABASE_PASSWORD=abcd123
      - DATABASE_USER=root

volumes:
  my-db: